Document: mvdir
Title: Debian mvdir Manual
Author: <insert document author here>
Abstract: This manual describes what mvdir is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mvdir/mvdir.sgml.gz

Format: postscript
Files: /usr/share/doc/mvdir/mvdir.ps.gz

Format: text
Files: /usr/share/doc/mvdir/mvdir.text.gz

Format: HTML
Index: /usr/share/doc/mvdir/html/index.html
Files: /usr/share/doc/mvdir/html/*.html
